"""create variants table

Revision ID: 0e9a0c1aa7b6
Revises: ec292f5d7884
Create Date: 2026-07-22 13:57:07.478691

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0e9a0c1aa7b6"
down_revision: str | None = "ec292f5d7884"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "variants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("variant_id", sa.String(length=255), nullable=False),
        sa.Column("chromosome", sa.String(length=10), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("ref", sa.String(length=500), nullable=False),
        sa.Column("alt", sa.String(length=500), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("quality", sa.Float(), nullable=True),
        sa.Column("filter_status", sa.String(length=50), nullable=True),
        sa.Column("genome_id", sa.UUID(), nullable=True),
        sa.Column("gene_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["gene_id"], ["genes.id"]),
        sa.ForeignKeyConstraint(["genome_id"], ["genomes.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_variants_variant_id"), "variants", ["variant_id"], unique=True)
    op.create_index(op.f("ix_variants_genome_id"), "variants", ["genome_id"], unique=False)
    op.create_index(op.f("ix_variants_gene_id"), "variants", ["gene_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_variants_variant_id"), table_name="variants")
    op.drop_index(op.f("ix_variants_genome_id"), table_name="variants")
    op.drop_index(op.f("ix_variants_gene_id"), table_name="variants")
    op.drop_table("variants")
    # ### end Alembic commands ###
