"""create genomes table

Revision ID: 0f3f64decdb7
Revises: 6ca189ad6980
Create Date: 2026-07-22 12:01:16.605164

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0f3f64decdb7"
down_revision: str | None = "6ca189ad6980"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genomes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("accession", sa.String(length=50), nullable=False),
        sa.Column("organism", sa.String(length=255), nullable=False),
        sa.Column("assembly", sa.String(length=100), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_genomes_accession"), "genomes", ["accession"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_genomes_accession"), table_name="genomes")
    op.drop_table("genomes")
    # ### end Alembic commands ###
