"""create samples table

Revision ID: 3c7e420e271b
Revises: 0f3f64decdb7
Create Date: 2026-07-22 12:40:40.765526

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3c7e420e271b"
down_revision: str | None = "0f3f64decdb7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "samples",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sample_id", sa.String(length=100), nullable=False),
        sa.Column("sample_name", sa.String(length=255), nullable=False),
        sa.Column("organism", sa.String(length=255), nullable=False),
        sa.Column("tissue", sa.String(length=255), nullable=True),
        sa.Column("cell_type", sa.String(length=255), nullable=True),
        sa.Column("disease", sa.String(length=255), nullable=True),
        sa.Column("phenotype", sa.String(length=255), nullable=True),
        sa.Column("sex", sa.String(length=20), nullable=True),
        sa.Column("age", sa.String(length=50), nullable=True),
        sa.Column("genome_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["genome_id"], ["genomes.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_samples_genome_id"), "samples", ["genome_id"], unique=False)
    op.create_index(op.f("ix_samples_sample_id"), "samples", ["sample_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_samples_sample_id"), table_name="samples")
    op.drop_index(op.f("ix_samples_genome_id"), table_name="samples")
    op.drop_table("samples")
    # ### end Alembic commands ###
