"""create transcripts table

Revision ID: 4a9d6aaf7429
Revises: 0e9a0c1aa7b6
Create Date: 2026-07-22 14:10:47.432499

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4a9d6aaf7429"
down_revision: str | None = "0e9a0c1aa7b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transcripts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("transcript_id", sa.String(length=50), nullable=False),
        sa.Column("transcript_name", sa.String(length=255), nullable=False),
        sa.Column("transcript_type", sa.String(length=50), nullable=True),
        sa.Column("chromosome", sa.String(length=10), nullable=False),
        sa.Column("strand", sa.String(length=1), nullable=True),
        sa.Column("start_position", sa.Integer(), nullable=True),
        sa.Column("end_position", sa.Integer(), nullable=True),
        sa.Column("length", sa.Integer(), nullable=True),
        sa.Column("genome_id", sa.UUID(), nullable=True),
        sa.Column("gene_id", sa.UUID(), nullable=True),
        sa.Column("variant_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["gene_id"], ["genes.id"]),
        sa.ForeignKeyConstraint(["genome_id"], ["genomes.id"]),
        sa.ForeignKeyConstraint(["variant_id"], ["variants.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transcripts_transcript_id"), "transcripts", ["transcript_id"], unique=True
    )
    op.create_index(
        op.f("ix_transcripts_genome_id"), "transcripts", ["genome_id"], unique=False
    )
    op.create_index(
        op.f("ix_transcripts_gene_id"), "transcripts", ["gene_id"], unique=False
    )
    op.create_index(
        op.f("ix_transcripts_variant_id"), "transcripts", ["variant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transcripts_variant_id"), table_name="transcripts")
    op.drop_index(op.f("ix_transcripts_transcript_id"), table_name="transcripts")
    op.drop_index(op.f("ix_transcripts_genome_id"), table_name="transcripts")
    op.drop_index(op.f("ix_transcripts_gene_id"), table_name="transcripts")
    op.drop_table("transcripts")
    # ### end Alembic commands ###
