"""create proteins table

Revision ID: cc42f7960492
Revises: 4a9d6aaf7429
Create Date: 2026-07-22 23:25:52.961090

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cc42f7960492"
down_revision: str | None = "4a9d6aaf7429"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proteins",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("protein_id", sa.String(length=50), nullable=False),
        sa.Column("protein_name", sa.String(length=255), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=True),
        sa.Column("accession", sa.String(length=50), nullable=True),
        sa.Column("sequence", sa.Text(), nullable=True),
        sa.Column("length", sa.Integer(), nullable=True),
        sa.Column("molecular_weight", sa.Float(), nullable=True),
        sa.Column("organism", sa.String(length=255), nullable=True),
        sa.Column("function", sa.Text(), nullable=True),
        sa.Column("gene_id", sa.UUID(), nullable=True),
        sa.Column("transcript_id", sa.UUID(), nullable=True),
        sa.Column("genome_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["gene_id"], ["genes.id"]),
        sa.ForeignKeyConstraint(["genome_id"], ["genomes.id"]),
        sa.ForeignKeyConstraint(["transcript_id"], ["transcripts.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_proteins_protein_id"), "proteins", ["protein_id"], unique=True
    )
    op.create_index(
        op.f("ix_proteins_accession"), "proteins", ["accession"], unique=False
    )
    op.create_index(
        op.f("ix_proteins_gene_id"), "proteins", ["gene_id"], unique=False
    )
    op.create_index(
        op.f("ix_proteins_transcript_id"), "proteins", ["transcript_id"], unique=False
    )
    op.create_index(
        op.f("ix_proteins_genome_id"), "proteins", ["genome_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_proteins_genome_id"), table_name="proteins")
    op.drop_index(op.f("ix_proteins_transcript_id"), table_name="proteins")
    op.drop_index(op.f("ix_proteins_gene_id"), table_name="proteins")
    op.drop_index(op.f("ix_proteins_accession"), table_name="proteins")
    op.drop_index(op.f("ix_proteins_protein_id"), table_name="proteins")
    op.drop_table("proteins")
    # ### end Alembic commands ###
