"""create genes table

Revision ID: ec292f5d7884
Revises: 3c7e420e271b
Create Date: 2026-07-22 13:35:15.741890

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ec292f5d7884"
down_revision: str | None = "3c7e420e271b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("gene_id", sa.String(length=50), nullable=False),
        sa.Column("gene_name", sa.String(length=255), nullable=False),
        sa.Column("chromosome", sa.String(length=10), nullable=False),
        sa.Column("strand", sa.String(length=1), nullable=True),
        sa.Column("start_position", sa.Integer(), nullable=True),
        sa.Column("end_position", sa.Integer(), nullable=True),
        sa.Column("biotype", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("genome_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["genome_id"], ["genomes.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_genes_gene_id"), "genes", ["gene_id"], unique=True)
    op.create_index(op.f("ix_genes_genome_id"), "genes", ["genome_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_genes_genome_id"), table_name="genes")
    op.drop_index(op.f("ix_genes_gene_id"), table_name="genes")
    op.drop_table("genes")
    # ### end Alembic commands ###
